# TP3 Analyse Numérique
# Mathys PRIMA - Ugo NOWAK groupe TP4

## Exercice 1:

1)

In [6]:
import numpy as np

In [169]:
def puissance(A, q0):
    x = np.zeros(len(A))
    lam = np.zeros(len(A))
    q0inf = np.zeros(len(A))
    q0_2 = np.zeros(len(A))
    cpt = 0
    while (cpt < 1000):
        for i in range(len(A)):
            x = np.dot(A, q0)
            if abs(q0[i]) > 1e-10:     
                lam[i] = x[i] / q0[i]
            q0[i] = (1/np.max(x)) * x[i]
            q0_2[i] = (1/np.linalg.norm(x)) * x[i]
        cpt += 1
    return q0, q0_2, lam    

2)

In [170]:
A = [(4,1,1),(1,3,0),(1,0,2)]
q0 = [1,1,1]

puissance(A,q0)

([1.0, 0.5320888862379561, 0.3472963553338607],
 array([0.84402963, 0.44909879, 0.29312841]),
 array([4.87938524, 4.87938524, 4.87938524]))

In [194]:
np.dot(A,puissance(A,q0)[0])-np.dot(puissance(A,q0)[2][0],puissance(A,q0)[0])

array([ 0.00000000e+00, -4.44089210e-16, -2.22044605e-16])

In [65]:
np.linalg.eig(q0)

EigResult(eigenvalues=array([4.87938524, 1.46791111, 2.65270364]), eigenvectors=array([[-0.84402963, -0.44909879,  0.29312841],
       [-0.44909879,  0.29312841, -0.84402963],
       [-0.29312841,  0.84402963,  0.44909879]]))

On remarque que le vecteur propre calculé avec la méthode de la puissanace (avec la norme infini) est différent du vecteur propre renvoyé par la fonction np.linalg.norm(x). Nous avons donc testé la méthode de la puissance avec la norme 2 et les résultats sont cette fois-ci similaires. Nous pouvons donc supposer que la norme influe sur le vecteur propre.

Nous avons utilisé l'IA (Claude AI) pour se renseigner sur les fonction np. existantes.

3)

In [66]:
def spectre(A):
    valeurs_propres = np.linalg.eig(A)
    return valeurs_propres[0]

In [68]:
B = [(4,3,2,1),(0,4j,3j,2j),(0,0,-4,-3),(0,0,0,-4j)]
spectre(B)

array([ 4.+0.j,  0.+4.j, -4.+0.j, -0.-4.j])

In [81]:
q0new = [1,1,1,1]
puissance(B,q0new)

C:\Users\ugonowak\AppData\Local\Temp\ipykernel_5328\2068329394.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  lam[i] = x[i]/q0[i]
C:\Users\ugonowak\AppData\Local\Temp\ipykernel_5328\2068329394.py:12: ComplexWarning: Casting complex values to real discards the imaginary part
  q0_2[i] = (1/np.linalg.norm(x))*x[i]


([(1+0j),
  (0.00014811998041047922+0.5718668067893193j),
  (-0.0011227106697272754+0.0010841882565400603j),
  (0.0007550619528037641-0.0036696554473097773j)],
 array([ 8.67816369e-01,  2.96930807e-04, -1.29165140e-03,  1.89574334e-03]),
 array([7.00787241e+00, 2.39490445e-03, 2.66842429e-02, 0.00000000e+00]))

Cela ne fonctionne pas ici avec la méthode de la puissance car il n'y a pas une unique valeur propre dominante (toutes les valeurs propres ont le même modules).

4)

In [78]:
def puissance_shift(A, q0, mu):
    x = np.zeros(len(A))
    lam = np.zeros(len(A))
    cpt = 0
    I = np.eye(len(A))
    B = A - mu * I
    
    while (cpt < 1000):
        x = np.zeros(len(A))
        x = np.linalg.solve(B, q0)
        gamma = x[np.argmax(np.abs(x))]
        for i in range(len(A)):
            q0[i] = x[i] / gamma
        cpt += 1
        
    return q0, lam

In [79]:
puissance_shift(B,q0new,3.9)

([(1+0j), 0j, -0j, 0j], array([0., 0., 0., 0.]))

Avec cette méthode cela fonctionne à la différence de la méthode de la puissance classique

## Exercice 2:

1)

In [182]:
def deflation(A, k):
    q1 = np.ones(len(A))
    q,q2,lamv = puissance(A,q1)
    lam = lamv[0]
    valeurs = [lam]
    vecteurs = [q]
    for i in range(1,k):      
        A = A - lam * np.dot(q, q)   
        q,q2,lamv = puissance(A,q1)
        lam = lamv[0]
        valeurs.append(lam)
        vecteurs.append(q)
    return valeurs, vecteurs

In [184]:
C = [(2,-1,0),(-1,2,-1),(0,-1,2)]
D = [(1,2,0,-1),(0,3,1,2),(2,0,4,1),(-1,1,0,2)]
lam,vecp = deflation(C,3)
print(lam,vecp)
print(np.linalg.norm(np.dot(C,vecp[0])-lam[0]*vecp[0]))

[3.414213562373095, -40.30898797920591, 328.1265332074853] [array([1.        , 0.99692427, 1.        ]), array([1.        , 0.99692427, 1.        ]), array([1.        , 0.99692427, 1.        ])]
4.822275673554959


In [185]:
q,q2,lamv = puissance(C,np.ones(len(C)))
print(np.linalg.norm(np.dot(C,q)-lam*q))

330.547314669777


In [177]:
np.linalg.eig(C)

EigResult(eigenvalues=array([3.41421356, 2.        , 0.58578644]), eigenvectors=array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
       [ 7.07106781e-01,  5.09486455e-16,  7.07106781e-01],
       [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))

In [179]:
deflation(D,4)

([4.799934335475221,
  -26.961595096115182,
  509.40826310147196,
  -7553.901495130898],
 [array([1.00066214, 1.00013242, 1.        , 1.00066207]),
  array([1.00066214, 1.00013242, 1.        , 1.00066207]),
  array([1.00066214, 1.00013242, 1.        , 1.00066207]),
  array([1.00066214, 1.00013242, 1.        , 1.00066207])])

In [128]:
np.linalg.eig(D)

EigResult(eigenvalues=array([0.03026577+0.j        , 2.58489995+0.44927782j,
       2.58489995-0.44927782j, 4.79993434+0.j        ]), eigenvectors=array([[-0.74027516+0.j        , -0.37126441+0.2164281j ,
        -0.37126441-0.2164281j ,  0.26278441+0.j        ],
       [ 0.13639894+0.j        , -0.47493558+0.0314951j ,
        -0.47493558-0.0314951j ,  0.55069569+0.j        ],
       [ 0.48507595+0.j        ,  0.71143145+0.j        ,
         0.71143145-0.j        ,  0.78556034+0.j        ],
       [-0.44507228+0.j        , -0.26421786-0.11322582j,
        -0.26421786+0.11322582j,  0.10282787+0.j        ]]))

In [124]:
deflation(A,3)

([4.879385241571817, -1.9815095512430552, 14.691129513802917],
 [array([2.88145258, 1.        , 1.19316958]),
  array([2.88145258, 1.        , 1.19316958]),
  array([2.88145258, 1.        , 1.19316958])])

Après avoir vérifié notre fonction puissance nous ne sommes pas parvenu à trouver l'erreur dans la fonction déflation. Nous concluons tout de même ue cette fonction est bien plus performante que la fonction puissance car nous pouvons obtenir toutes les valeurs propres ainsi que les vecteurs propres associés.

Nous avons de nouveau utilisé Claude AI pour rechercher les fonctions numpy utiles ici ainsi que pour essayer de trouver ce qui ne fonctionne pas (sans succès)